#ifndef _SEA_URCHIN_SEA_URCHIN_H_
#define _SEA_URCHIN_SEA_URCHIN_H_

#define SEA_URCHIN_ERROR_OBJECT_IS_NULL                 1
#define SEA_URCHIN_ERROR_OUT_IS_NULL                    2
#define SEA_URCHIN_ERROR_ITEM_IS_NULL                   3
#define SEA_URCHIN_ERROR_VALUE_IS_NULL                  4
#define SEA_URCHIN_ERROR_OTHER_IS_NULL                  5
#define SEA_URCHIN_ERROR_MEMORY_ALLOCATION_FAILED       6
#define SEA_URCHIN_ERROR_IS_EMPTY                       7
#define SEA_URCHIN_ERROR_END_OF_SEQUENCE                8
#define SEA_URCHIN_ERROR_INDEX_IS_OUT_OF_BOUNDS         9
#define SEA_URCHIN_ERROR_ITEM_IS_OUT_OF_BOUNDS          10
#define SEA_URCHIN_ERROR_STREAM_IS_NULL                 11
#define SEA_URCHIN_ERROR_FUNCTION_IS_NULL               12
#define SEA_URCHIN_ERROR_VALUE_ALREADY_EXISTS           13
#define SEA_URCHIN_ERROR_VALUE_NOT_FOUND                14
#define SEA_URCHIN_ERROR_ITEM_NOT_FOUND                 15
#define SEA_URCHIN_ERROR_KEY_IS_NULL                    16
#define SEA_URCHIN_ERROR_VALUE_IS_INVALID               17
#define SEA_URCHIN_ERROR_VALUE_IS_TOO_LARGE             18
#define SEA_URCHIN_ERROR_VALUE_IS_NEGATIVE              19
#define SEA_URCHIN_ERROR_RESULT_IS_INCONSISTENT         20
#define SEA_URCHIN_ERROR_RESULT_IS_UNCHANGED            21
#define SEA_URCHIN_ERROR_DIVIDE_BY_ZERO                 22
#define SEA_URCHIN_ERROR_VALUE_IS_ZERO                  23
#define SEA_URCHIN_ERROR_KEY_IS_TOO_LARGE               24
#define SEA_URCHIN_ERROR_OPERATION_UNAVAILABLE          25

#endif /* _SEA_URCHIN_SEA_URCHIN_H_ */
